language: python # Set the build language to Python

python: 3.8 # Set the version of Python to use

install:
    - pip install mkdocs # Install the required dependencies

script: true # Skip script (Don't use this if one already exists)

before_deploy:
    - mkdocs build --verbose --clean --strict # Build a local version of the docs

# deploy: # Deploy documentation to Github in the gh_pages branch
#     provider: pages
#     skip_cleanup: true
#     github_token: $github_token
#     local_dir: site
#     on:
#         branch: master

